openapi: 3.0.0
info:
  title: Space Marines Service
  version: 1.0.0
  description: API для взаимодействия с коллекцией космических десантников
servers:
  - url: 'https://localhost:8080/space-marines-service'

paths:
  /space-marines:
    post:
      summary: Создание нового десантника (призыв)
      tags:
        - SpaceMarines
      operationId: createSpaceMarine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpaceMarine"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpaceMarine"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: ['Координата х не может быть больше 683']
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
    get:
      summary: Получение всех десантников (отмечаем в военкомате)
      tags:
        - SpaceMarines
      operationId: getSpaceMarine
      parameters:
        - name: limit
          in: query
          description: Количество элементов в выдаче
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          description: Сдвиг по элементам от начала
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: sortBy
          in: query
          description: Параметры для сортировки
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - id
                - name
                - creationDate
                - health
                - height
                - category
            example: name
        - name: sortDirection
          in: query
          description: Направление сортировки
          required: false
          schema:
            type: string
            default: ASC
            enum:
              - ASC
              - DESC
            example: ASC
        - name: minId
          in: query
          description: Минимальный айди десантника
          required: false
          schema:
            type: integer
            minimum: 1
            example: 25
        - name: maxId
          in: query
          description: Максимальный айди десантника
          required: false
          schema:
            minimum: 1
            type: integer
            example: 50
        - name: name
          in: query
          description: Имя десантника
          required: false
          schema:
            type: string
            minLength: 1
            example: Серж
        - name: minX
          in: query
          description: Минимальная координата х
          required: false
          schema:
            type: number
            format: float
            example: -1337.3
        - name: maxX
          in: query
          description: Максимальная координата х
          required: false
          schema:
            type: number
            format: float
            example: 1337.3
        - name: minY
          in: query
          description: Минимальная координата y
          required: false
          schema:
            type: number
            format: double
            example: -1337.3
        - name: maxY
          in: query
          description: Максимальная координата y
          required: false
          schema:
            type: number
            format: double
            example: 1337.3
        - name: minCreationDate
          in: query
          description: Дата создания должна быть позже...
          required: false
          schema:
            type: string
            format: date
            nullable: false
            example: 2007-07-13
        - name: maxCreationDate
          in: query
          description: Дата создания должна быть позже или равна...
          required: false
          schema:
            type: string
            format: date
            nullable: false
            example: 2024-09-30
        - &minHealth
          name: minHealth
          in: query
          description: Минимальное здоровье
          required: false
          schema:
            type: number
            format: float
            minimum: 0
            example: 1337.3
        - name: maxHealth
          in: query
          description: Максимальное здоровье
          required: false
          schema:
            type: number
            format: float
            minimum: 0
            example: 1337.3
        - name: loyal
          in: query
          description: Верный императору (че)
          required: false
          schema:
            type: boolean
        - name: minHeight
          in: query
          description: Минимальный рост
          required: false
          schema:
            type: number
            format: double
            example: 1337.3
        - name: maxHeight
          in: query
          description: Максимальный рост
          required: false
          schema:
            type: number
            format: double
            example: 1337.3
        - name: category
          in: query
          description: Масть
          required: false
          schema:
            type: string
            enum:
              - DREADNOUGHT
              - INCEPTOR
              - SUPPRESSOR
              - TERMINATOR
              - LIBRARIAN
            example: SUPPRESSOR
        - name: chapterName
          in: query
          description: Часть
          required: false
          schema:
            type: string
            minLength: 1
            example: third
        - name: chapterWorld
          in: query
          description: Мир
          required: false
          schema:
            type: string
            minLength: 1
            example: outworld
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SpaceMarine"
                  total:
                    type: integer
                    description: Общее количество элементов
                  limit:
                    type: integer
                    description: Количество элементов
                  offset:
                    type: integer
                    description: Сдвиг по элементам
        '204':
          description: No content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: Неправильные параметры
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /space-marines/{space-marine-id}:
    get:
      summary: Получение десантника по идентификатору (сер да сер)
      tags:
        - SpaceMarines
      operationId: getSpaceMarineById
      parameters:
        - &space-marine-id
          name: space-marine-id
          description: Идентификатор десантника
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ с данными о призывнике
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpaceMarine"
        '404':
          description: Not found
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
    put:
      summary: Обновление десантника (мобилизация)
      tags:
        - SpaceMarines
      operationId: updateSpaceMarine
      parameters:
        - *space-marine-id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpaceMarine"
      responses:
        '204':
          description: Updated
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: [ 'Координата х не может быть больше 683' ]
        '404':
          description: Not found
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
    delete:
      summary: Удаление десантника по идентификатору (ура дембель)
      tags:
        - SpaceMarines
      operationId: deleteSpaceMarineById
      parameters:
        - name: space-marine-id
          description: Идентификатор десантника
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешный ответ
          content:
            application/json: {}
        '404':
          description: Not found
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /space-marines/categories/{category}:
    delete:
      summary: Удаление десантника по классу
      description: Регистронезависимый запрос
      tags:
        - SpaceMarines
      operationId: deleteSpaceMarineByCategory
      parameters:
        - name: category
          description: Класс десантника
          in: path
          required: true
          schema:
            nullable: true
            type: string
            enum:
              - DREADNOUGHT
              - INCEPTOR
              - SUPPRESSOR
              - TERMINATOR
              - LIBRARIAN
      responses:
        '204':
          description: Успешный ответ
          content:
            application/json: {}
        '400':
          description: Bad request
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /space-marines/loyalists:
    get:
      summary: Получение любого лояльного десантника
      tags:
        - SpaceMarines
      operationId: getLoyalSpaceMarine
      responses:
        '200':
          description: Любой лояльный десантник
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '204':
          description: No content
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /space-marines/amount:
    get:
      summary: Получение всех здоровых десантников
      tags:
        - SpaceMarines
      parameters:
        - *minHealth
      operationId: getSpaceMarinesWithHealthMoreThenGiven
      responses:
        '200':
          description: Успешный ответ со всеми здоровыми десантниками
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AmountResponse"
        '204':
          description: No content
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        default:
          description: Дефолтная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'

components:
  schemas:
    SpaceMarine:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          uniqueItems: true
          readOnly: true
        name:
          type: string
          minLength: 1
          nullable: false
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
          readOnly: true
          default: 2004-01-26
        health:
          type: number
          format: float
          minimum: 1
          nullable: false
        loyal:
          type: boolean
          nullable: false
        height:
          type: number
          format: double
          nullable: false
        category:
          $ref: '#/components/schemas/AstartesCategory'
        chapter:
          $ref: '#/components/schemas/Chapter'
        starship:
          $ref: '#/components/schemas/Starship'
          readOnly: true
      required:
        - name
        - coordinates
        - creationDate
        - numberOfParticipants
        - description
        - genre

    Coordinates:
      type: object
      nullable: false
      properties:
        x:
          type: number
          format: float
          nullable: false
        y:
          type: number
          format: double
          maximum: 683
          nullable: false
      required:
        - x
        - y

    AstartesCategory:
      nullable: true
      type: string
      enum:
        - DREADNOUGHT
        - INCEPTOR
        - SUPPRESSOR
        - TERMINATOR
        - LIBRARIAN

    Chapter:
      type: object
      nullable: false
      properties:
        name:
          type: string
          minLength: 1
          nullable: false
        world:
          type: string
          nullable: true
      required:
        - name
        - world

    AmountResponse:
      type: object
      nullable: false
      properties:
        amount:
          type: integer
          format: int64
          nullable: false

    Starship:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
          nullable: false
        name:
          type: string
          nullable: false

    DefaultError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 418
        message:
          type: string
          example: Ты чайник